//<auto-generated />

using Nebim.Era.Plt.Comm.Customer.Application.Contracts;
using Refit;

namespace Nebim.Era.Plt.Comm.Customer.HttpClient
{
    public partial interface ICustomersApi
    {
        [Get("/customers")]
        Task<List<CustomerResponse>> List(int? skip = null, int? top = null, string filter = null, string orderBy = null);

        [Get("/customers/{id}")]
        Task<CustomerResponse> Get(Guid id);

        [Get("/customers/:passportinfo")]
        Task<List<CustomerResponse>> GetByPassportInfo(string passportNumber = null, string firstName = null, string lastName = null, int? countryId = null);

        [Post("/customers")]
        Task<CustomerResponse> Create([Body] CreateCustomerRequest request);

        [Put("/customers")]
        Task Update([Body] UpdateCustomerRequest request);

        [Delete("/customers/{id}")]
        Task Delete(Guid id);

        [Post("/customers/{customerId}/address")]
        Task<CustomerResponse> AddCustomerAddress([Body] AddCustomerAddressRequest request, Guid customerId);

        [Delete("/customers/{customerId}/address/{customerAddressId}")]
        Task DeleteCustomerAddress(Guid customerId, Guid customerAddressId);

        [Put("/customers/{customerId}/address/{customerAddressId}")]
        Task UpdateCustomerAddress([Body] UpdateCustomerAddressRequest request, Guid customerId, Guid customerAddressId);

        [Post("/customers/import")]
        Task<List<CustomerResponse>> ImportCustomer([Body] ImportCustomerRequest request);
    }
}
