//<auto-generated />

using Nebim.Era.Plt.Comm.Customer.Application.Contracts;
using Refit;

namespace Nebim.Era.Plt.Comm.Customer.HttpClient
{
    public partial interface IPassportsApi
    {
        [Get("/passports")]
        Task<IEnumerable<PassportResponse>> List(int? skip = null, int? top = null, string filter = null, string orderBy = null);

        [Get("/passports/{id}")]
        Task<PassportResponse> Get(Guid id);

        [Get("/passports/customer/{customerId}")]
        Task<PassportResponse> GetByCustomerId(Guid customerId);

        [Post("/passports")]
        Task<PassportResponse> Create([Body] CreatePassportRequest request);

        [Put("/passports")]
        Task Update([Body] UpdatePassportRequest request);

        [Delete("/passports/{id}")]
        Task Delete(Guid id);
    }
}
