#!/bin/bash

GITHUB_USERNAME=$1
GITHUB_ACCESS_TOKEN=$2
GITHUB_PACKAGE_URL=$3
REPOSITORY_URI=$4
VERSION=$5

docker build --build-arg GITHUB_USERNAME=$GITHUB_USERNAME --build-arg GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN --build-arg GITHUB_PACKAGE_URL=$GITHUB_PACKAGE_URL -t $REPOSITORY_URI:$VERSION .
